### ISSUE TITLE
Tag Releases

### ISSUE THREAD

**Issue by Arszilla** [RoseSecurity/ScrapPY#7]
Hey there,

I am packaging ScrapPY for Kali right now, as per https://bugs.kali.org/view.php?id=8064. Since you already have tags (`0.1.0`), it would be beneficial to have a new tag for the recent changes you've made to the repo before I start packaging.

If you could kindly release a new tag, I'd appreciate it.

Kind regards.

**Comment by RoseSecurity** [comment]
Hey @Arszilla

Just created a new [release](https://github.com/RoseSecurity/ScrapPY/releases/tag/0.1.1) for the packaging! Thank you for taking this on and I look forward to seeing the tool added to the distro.
